#!/bin/sh
#kvm -drive file=linux/img/sanos.vmdk,if=virtio,boot=on -net user -net nic -redir tcp:2323::23 -redir tcp:8080::80
qemu-system-x86_64 -sdl -enable-kvm -drive file=linux/img/sanos.vmdk,if=virtio -net user -net nic,model=rtl8139 -redir tcp:2323::23 -redir tcp:8080::80
