#
# Makefile for awk
#

CCFLAGS=-D FOPEN_MAX=40 -I . -D USE_LOCAL_HEAP

all: awk.exe 

SRCS=b.c main.c parse.c proctab.c tran.c lib.c run.c lex.c ytab.c

awk.exe: $(SRCS)
	$(CC) -o awk.exe $(SRCS) $(CCFLAGS)

install: awk.exe
  cp awk.exe /usr/bin/awk.exe

clean:
  rm awk.exe

