#
# Makefile for unzip
#

CC=../../../linux/tools/cc
CCFLAGS=-B ../../../linux/install/usr -D USE_LOCAL_HEAP -D UNIX

all: unzip.exe

SRCS= \
	unzip.c \
	crc32.c \
	crypt.c \
	envargs.c \
	explode.c \
	extract.c \
	fileio.c \
	globals.c \
	inflate.c \
	list.c \
	match.c \
	process.c \
	ttyio.c \
	ubz2err.c \
	unreduce.c \
	unshrink.c \
	zipinfo.c \
	unix.c

unzip.exe: $(SRCS)
	$(CC) -o unzip.exe $(SRCS) $(CCFLAGS)

