#
# Makefile for yacc
#

HDRS=defs.h
SRCS=closure.c error.c graph.c lalr.c lr0.c main.c mkpar.c output.c reader.c skeleton.c symtab.c verbose.c warshall.c

all: yacc.exe 

yacc.exe: $(SRCS) $(HDRS)
	$(CC) -o yacc.exe $(SRCS) $(CCFLAGS)

install: yacc.exe
  cp yacc.exe /usr/bin/yacc.exe

clean:
  rm yacc.exe

