#
# Makefile for yacc
#

CC=../../../linux/tools/cc
CCFLAGS=-B ../../../linux/install/usr -D USE_LOCAL_HEAP

HDRS=defs.h
SRCS=closure.c error.c graph.c lalr.c lr0.c main.c mkpar.c output.c reader.c skeleton.c symtab.c verbose.c warshall.c

all: yacc.exe 

yacc.exe: $(SRCS) $(HDRS)
	$(CC) -o yacc.exe $(SRCS) $(CCFLAGS)

