#
# Makefile for zip
#

CC=../../../linux/tools/cc
CCFLAGS=-B ../../../linux/install/usr -D USE_LOCAL_HEAP -D UNIX -D NOGETOPTION

all: zip.exe

SRCS= \
	zip.c \
	zipfile.c \
	zipup.c \
	fileio.c \
	util.c \
	crc32.c \
	globals.c \
	deflate.c \
	trees.c \
	crypt.c \
	ttyio.c \
	unix.c

zip.exe: $(SRCS)
	$(CC) -o zip.exe $(SRCS) $(CCFLAGS)

